-- Preguntas AZ-900 (estilo AWS CCP del proyecto)
-- Ejecutar después de estructura.sql

INSERT INTO modulos (id, nombre, descripcion, icono)
SELECT 6, 'Azure AZ-900', 'Fundamentos de Azure: modelos cloud, identidad, seguridad, gobernanza, costes y soporte', 'fa-cloud'
WHERE NOT EXISTS (SELECT 1 FROM modulos WHERE id = 6);

INSERT INTO preguntas (modulo_id, pregunta, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, explicacion, dificultad) VALUES
(6, 'En una solución PaaS para aplicaciones web en Azure, ¿cuál afirmación es correcta?',
'Exige configurar hipervisores y redes físicas en cada región utilizada',
'Requiere administrar parches del sistema operativo de cada nodo web manualmente',
'Escala automáticamente la plataforma sin administrar el sistema operativo base',
'Impide usar frameworks modernos para desarrollar aplicaciones en la nube',
'C', 'En PaaS Azure gestiona la infraestructura base y permite escalado automático de la plataforma.', 'facil'),

(6, 'Respecto a CapEx y OpEx en Azure, ¿qué enunciado es correcto?',
'CapEx y OpEx son idénticos en la nube y no cambian por consumo real',
'Azure permite mover gasto a OpEx y pagar por uso con flexibilidad financiera',
'Dos VM B2s siempre cuestan igual cada mes sin importar horas de ejecución',
'Apagar una VM elimina automáticamente todos los costes de almacenamiento asociado',
'B', 'Azure permite flexibilidad entre CapEx y OpEx con consumo medido y pago por uso.', 'facil'),

(6, 'Cuando implementas una solución SaaS, ¿de qué es responsable el cliente?',
'Definir clústeres físicos y reemplazar hardware del proveedor',
'Instalar hipervisores y configurar redes troncales del datacenter',
'Configurar la solución SaaS según sus usuarios, datos y procesos de negocio',
'Parchear el sistema operativo host donde corre la aplicación del proveedor',
'C', 'En SaaS el cliente configura la aplicación (usuarios, reglas, datos), no la infraestructura.', 'facil'),

(6, 'Una organización que migra su infraestructura a ______ no requerirá datacenter propio para esa carga.',
'Nube privada autogestionada en instalaciones corporativas dedicadas',
'Nube híbrida con cargas críticas siempre ejecutadas en local',
'Host Hyper-V instalado en un rack de la oficina principal',
'Nube pública con servicios gestionados por el proveedor cloud',
'D', 'En nube pública el proveedor opera la infraestructura física.', 'facil'),

(6, '¿Cuál opción incluye DOS características típicas de nube pública?',
'Recursos aislados sin portal de gestión ni APIs de automatización',
'Hardware dedicado para cada cliente y capacidad fija no elástica',
'Almacenamiento permanentemente limitado y redes sin cifrado empresarial',
'Pago por uso medido y aprovisionamiento autoservicio bajo demanda',
'D', 'La nube pública ofrece autoservicio y cobro por consumo.', 'facil'),

(6, 'Para migrar una aplicación web y minimizar la administración de plataforma, ¿qué recomendarías?',
'IaaS con máquinas virtuales y actualización manual de sistema operativo',
'PaaS con Azure App Service y escalado administrado por plataforma',
'SaaS de correo corporativo para reemplazar la aplicación existente',
'DaaS enfocada solo en base de datos sin capa de aplicación web',
'B', 'PaaS reduce esfuerzo operativo al abstraer servidores y parches.', 'facil'),

(6, 'Para 10 apps web con dominios personalizados, 10 GB y bajo costo, ¿qué plan de App Service encaja mejor?',
'Plan Free con cuota compartida y sin soporte sólido para dominios productivos',
'Plan Shared con recursos multi-tenant y sin instancias dedicadas estables',
'Plan Basic con instancias dedicadas, dominios personalizados y coste contenido',
'Plan PremiumV3 con máximo rendimiento y coste superior al requisito planteado',
'C', 'Basic suele cubrir dominios personalizados e instancias dedicadas minimizando coste frente a planes altos.', 'medio'),

(6, '¿Qué combinación relaciona correctamente los conceptos de resiliencia y rendimiento?',
'DR: sigue activo sin fallos | Tolerancia: recupera después | Latencia: lenta | Escala: fija',
'DR: cifrado | Tolerancia: auditoría | Latencia: backup | Escala: capacidad mínima',
'DR: firewall | Tolerancia: antivirus | Latencia: enlace dedicado | Escala: vertical',
'DR: recuperarse tras fallo | Tolerancia: seguir disponible | Baja latencia: acceso rápido | Escalabilidad: mantener rendimiento al crecer demanda',
'D', 'Es la definición estándar de cada concepto en fundamentos cloud.', 'facil'),

(6, 'Una app en Azure que consulta SQL Server local es ejemplo de qué modelo?',
'Nube pública pura sin dependencia de infraestructura local conectada',
'Nube privada porque cualquier base de datos local fuerza todo el modelo',
'Nube híbrida por integrar recursos cloud con recursos on-premises',
'Nube multi-vendor al usar dos productos del mismo proveedor tecnológico',
'C', 'Combina componentes en Azure y en local: modelo híbrido.', 'facil'),

(6, 'Sobre OpEx, ¿cuál afirmación es correcta?',
'Construir un datacenter es OpEx mensual porque no compra activos',
'Apagar una suscripción cloud convierte automáticamente todo gasto en CapEx',
'Comprar terreno y servidores propios se registra normalmente como OpEx',
'Sueldos técnicos y software en suscripción son ejemplos típicos de OpEx',
'D', 'OpEx incluye gastos operativos recurrentes como salarios y licencias por suscripción.', 'facil'),

(6, 'Si deseas delegar permisos a varias VMs de Azure simultáneamente, conviene agruparlas:',
'En el mismo grupo de recursos para facilitar asignaciones RBAC consistentes',
'En la misma zona de disponibilidad para heredar permisos automáticamente',
'En la misma plantilla ARM porque la plantilla controla permisos en ejecución',
'En una región única ya que RBAC solo funciona dentro de una región',
'A', 'Agrupar recursos facilita asignar roles RBAC en un único alcance.', 'facil'),

(6, '¿Cuál enunciado sobre Resource Groups es correcto?',
'Los recursos solo pueden comunicarse si están en el mismo grupo de recursos',
'Al eliminar un Resource Group se eliminan también sus recursos contenidos',
'Un Resource Group solo admite recursos de una única región obligatoriamente',
'No se pueden aplicar bloqueos ni etiquetas a nivel de Resource Group',
'B', 'Borrar un Resource Group elimina los recursos que contiene.', 'facil'),

(6, 'Para almacenar 25 TB de datos poco frecuentes y analizarlos con Power BI, ¿qué recomendar?',
'Azure Cosmos DB y Azure SQL Database para transacciones OLTP de baja latencia',
'Azure Database for PostgreSQL y Azure SQL Managed Instance en alta concurrencia',
'Azure Data Lake Storage y un motor analítico como Synapse para consumo BI',
'Azure Cache for Redis y Service Bus para consultas ad hoc de archivos masivos',
'C', 'Data Lake + analítica es adecuado para grandes volúmenes con acceso menos frecuente.', 'medio'),

(6, '¿Para qué tipo de fallo protege principalmente una zona de disponibilidad?',
'Caída total de todas las regiones de Azure en un continente completo',
'Error lógico en una aplicación desplegada sin redundancia entre instancias',
'Pérdida de credenciales por mala gestión de identidades en la organización',
'Fallo de un datacenter específico dentro de la misma región de Azure',
'D', 'Las Availability Zones aíslan fallos de datacenter dentro de una región.', 'facil'),

(6, 'Corrige la frase: “Los Resource Groups administran cumplimiento en varias suscripciones”.',
'Debe decir Azure Policy, que evalúa y aplica cumplimiento sobre recursos',
'No requiere cambios porque Resource Groups gobiernan cumplimiento multi-suscripción',
'Debe decir App Service Plan, que centraliza reglas de cumplimiento corporativo',
'Debe decir Azure Bastion, que define estándares regulatorios por suscripción',
'A', 'El cumplimiento normativo se gestiona con Azure Policy, no con Resource Groups.', 'facil'),

(6, 'Sobre suscripciones de Azure, ¿qué afirmación es correcta?',
'No puedes usar una sola cuenta para administrar varias suscripciones',
'Una empresa puede usar recursos distribuidos en varias suscripciones',
'Dos suscripciones siempre se fusionan en una automáticamente por inactividad',
'Los recursos de distintas suscripciones no pueden compartir identidad corporativa',
'B', 'Una organización puede operar múltiples suscripciones bajo la misma identidad.', 'facil'),

(6, 'Para conectar red local con VMs en Azure mediante VPN, ¿qué DOS recursos son clave?',
'Load Balancer y Application Gateway para crear túneles sitio a sitio',
'Azure Firewall y DDoS Protection para direccionar rutas BGP de la VPN',
'Virtual Network Gateway y Gateway Subnet dentro de una Virtual Network',
'Azure Front Door y Traffic Manager para cifrar tráfico interno del túnel',
'C', 'VPN Gateway requiere Gateway Subnet en una VNet para conexión híbrida.', 'medio'),

(6, 'Para mapear una unidad de red desde Windows 10 hacia Azure Storage, ¿qué recurso usar?',
'Azure SQL Database para compartir archivos SMB entre equipos de escritorio',
'Disco de datos adjunto a VM para exponer recursos de red sin servidor',
'Servicio Blob para montar unidades SMB nativas en explorador de archivos',
'Azure Files en una Storage Account para compartir vía SMB administrado',
'D', 'Azure Files ofrece comparticiones SMB para mapear unidades de red.', 'facil'),

(6, 'Necesitas multi-región de escritura y documentos JSON. ¿Qué base de datos usar?',
'Azure Cosmos DB con replicación global y APIs para documentos JSON',
'Azure Database for MySQL en modo single-region con réplicas de lectura',
'Azure SQL Database Hyperscale sin modelo de documentos nativo JSON multi-write',
'Azure Cache for Redis como almacén primario transaccional multi-región',
'A', 'Cosmos DB soporta distribución global y modelo de documentos JSON.', 'facil'),

(6, '¿Qué mapeo de servicios es correcto?',
'Code sin servidor: App Service | Big data ML: Advisor | anomalías: DevOps',
'Code sin servidor: Functions | Big data: Databricks | anomalías: App Insights | web hosting: App Service',
'Code sin servidor: VNet | Big data: NSG | anomalías: Key Vault | web: Bastion',
'Code sin servidor: SQL DB | Big data: Cosmos DB | anomalías: Sentinel | web: DNS',
'B', 'Functions, Databricks, Application Insights y App Service encajan con esas descripciones.', 'facil'),

(6, 'Si creas y eliminas muchas VMs de prueba cada semana, ¿qué servicio reduce más la gestión?',
'Instancias reservadas, diseñadas para cargas estables de largo plazo',
'VM Scale Sets, orientado a escalado homogéneo continuo en producción',
'Azure DevTest Labs para aprovisionamiento y ciclo de vida de entornos de prueba',
'Windows 365, centrado en escritorios cloud persistentes para usuarios finales',
'C', 'DevTest Labs optimiza laboratorios y ciclos frecuentes de creación/eliminación.', 'medio'),

(6, 'Para ejecutar Azure CLI desde un PC local, ¿qué DOS herramientas puedes usar?',
'Símbolo del sistema y Windows PowerShell para ejecutar comandos az',
'Azure Resource Explorer y Defender Firewall para lanzar scripts CLI',
'Centro de redes y recursos compartidos y Event Viewer con módulo az',
'Editor del Registro y Monitor de recursos como shells de automatización',
'A', 'Azure CLI puede ejecutarse desde cmd o PowerShell en Windows.', 'facil'),

(6, 'Completa la frase: ________ es un servicio analítico basado en Apache Spark.',
'Azure Data Factory con orquestación ETL como motor Spark principal',
'Azure Databricks como plataforma analítica colaborativa sobre Apache Spark',
'Azure DevOps con pipelines YAML para ejecución distribuida Spark nativa',
'Azure Monitor con áreas de trabajo para procesamiento Spark administrado',
'B', 'Azure Databricks es el servicio Spark administrado en Azure.', 'facil'),

(6, 'Sobre Azure Monitor, ¿cuál afirmación es correcta?',
'No admite datos de equipos locales ni de otras nubes conectadas',
'No puede enviar alertas a grupos ni acciones automatizadas empresariales',
'Permite supervisión híbrida y alertas basadas en Log Analytics Workspace',
'Solo monitorea recursos IaaS y no aplicaciones ni telemetría personalizada',
'C', 'Azure Monitor admite escenarios híbridos y alertas sobre métricas y logs.', 'medio'),

(6, 'Para ver incidencias de plataforma que afecten la disponibilidad de una VM, usa:',
'Azure Service Fabric para consultar eventos de mantenimiento global',
'Azure Advisor para recibir incidentes críticos operativos en tiempo real',
'Azure Monitor Workbook como única fuente oficial de estado regional',
'Azure Service Health para notificaciones sobre incidentes y mantenimientos',
'D', 'Service Health informa incidencias de servicios por suscripción/región.', 'facil'),

(6, '¿Qué asociación de herramientas es correcta?',
'Azure DevOps despliegue de código | Azure Advisor recomendaciones | Cognitive Services IA preconstruida | App Insights monitorización',
'Azure Policy despliegue de código | Defender IA preconstruida | Log Analytics CI/CD',
'Bastion despliegue de código | Front Door recomendaciones | Databricks monitorización',
'Cosmos DB despliegue de código | Cost Management IA preconstruida | NSG monitorización',
'A', 'Ese mapeo corresponde a capacidades reales de cada servicio.', 'facil'),

(6, 'Para proteger sitios web ante ataques y obtener reportes detallados, ¿qué servicio incluir?',
'Azure Firewall como WAF L7 integrado para aplicaciones web públicas',
'NSG con reglas L3/L4 como solución principal de protección web avanzada',
'Azure Information Protection para filtrar tráfico HTTP malicioso en borde',
'Azure DDoS Protection para mitigar ataques volumétricos y generar telemetría',
'D', 'DDoS Protection ayuda ante ataques de denegación de servicio y aporta métricas/reportes.', 'medio'),

(6, '¿Qué servicio de Azure se asocia a “supervisar amenazas mediante sensores”?',
'Azure Monitor, orientado a métricas y trazas de rendimiento operativo',
'Microsoft Defender for Cloud (antes Security Center) para postura y amenazas',
'Azure AD Identity Protection, centrado en riesgos de identidad de usuarios',
'Microsoft Defender for Identity (antes Azure ATP), basado en sensores de AD',
'D', 'Defender for Identity usa sensores para detectar amenazas en identidades.', 'medio'),

(6, 'Sobre Network Security Groups (NSG), ¿qué afirmación es correcta?',
'Se puede asociar un NSG a una subred y también a una interfaz de red',
'Se puede asociar un NSG directamente al tenant para todas las VNets',
'Se puede asociar un NSG a la región completa sin recursos intermedios',
'Se puede asociar un NSG a una suscripción para herencia automática total',
'A', 'NSG se asocia a subredes y/o NICs, no a VNet completa directamente.', 'facil'),

(6, 'Para limitar tráfico entrante de múltiples VNets de forma centralizada, ¿qué crear?',
'Application Security Groups para filtrado perimetral central multi-red',
'Un Azure Firewall como punto central de control de tráfico de entrada',
'Diez Virtual Network Gateways, uno por VNet, para reemplazar firewall',
'Azure Security Center como dispositivo en línea de inspección de paquetes',
'B', 'Azure Firewall centraliza filtrado y control de tráfico entre redes.', 'facil'),

(6, 'Para cifrar y proteger credenciales administrativas en despliegues automatizados, usa:',
'Azure Policy con efecto deny para ocultar secretos en plantillas ARM',
'Azure Information Protection para secretos de infraestructura como servicio',
'Azure Key Vault para almacenar y usar secretos, claves y certificados',
'Azure MFA para cifrar contraseñas embebidas en archivos de despliegue',
'C', 'Key Vault es el servicio adecuado para gestionar secretos de forma segura.', 'facil'),

(6, 'Señala la opción FALSA sobre Azure:',
'Se pueden crear roles RBAC personalizados para controlar acceso',
'Una cuenta de usuario puede tener múltiples roles en distintos alcances',
'Un Resource Group puede tener varios propietarios asignados',
'Al detener una VM nunca se pagan costes de almacenamiento asociados',
'D', 'Aunque detengas VM, el almacenamiento (discos) sigue generando coste.', 'facil'),

(6, 'Para recopilar y analizar eventos de seguridad de Azure AD automáticamente, usarías:',
'Azure Sentinel (Microsoft Sentinel) como SIEM/SOAR en la nube',
'Azure Synapse Analytics para reemplazar auditoría de identidades en tiempo real',
'Azure AD Connect como motor SIEM de correlación de eventos de seguridad',
'Azure Key Vault para consultas KQL y respuesta automática a incidentes',
'A', 'Microsoft Sentinel centraliza análisis y respuesta de seguridad.', 'medio'),

(6, 'Completa la frase: “Su empresa implementa ______ para agregar marcas de agua a documentos”.',
'Azure Policy para clasificar y etiquetar contenido documental automáticamente',
'Azure Information Protection para etiquetado, clasificación y protección documental',
'Azure DDoS Protection para aplicar marcas visuales en archivos Office',
'Azure AD Identity Protection para insertar sellos en PDFs corporativos',
'B', 'AIP permite clasificar/proteger información, incluyendo etiquetado.', 'facil'),

(6, 'Para seguimiento de normativas y estándares regulatorios corporativos, el servicio correcto es:',
'Azure Cloud Shell con scripts Bash de cumplimiento nativo por defecto',
'Partner Center con panel operativo de cumplimiento de suscripción final',
'Compliance Manager del Microsoft Purview compliance portal',
'Azure Policy como repositorio único de certificados ISO corporativos',
'C', 'Compliance Manager ayuda a evaluar y seguir cumplimiento regulatorio.', 'medio'),

(6, '¿Qué documento explica qué datos procesa Microsoft y con qué propósito?',
'La declaración de privacidad de Microsoft con detalles de tratamiento de datos',
'Los SLA de Microsoft, centrados en disponibilidad y créditos de servicio',
'Los Product Terms, centrados en licenciamiento y condiciones comerciales',
'El contrato de suscripción de Azure, centrado en relación contractual',
'A', 'La declaración de privacidad aborda tratamiento y finalidad de los datos.', 'facil'),

(6, 'Una iniciativa de Azure Policy es:',
'Una colección de definiciones de políticas para aplicar objetivos comunes',
'Una colección de asignaciones RBAC de seguridad por recurso',
'Un grupo de definiciones de Azure Blueprints ya deprecadas por defecto',
'Una colección de alertas de Azure Monitor para auditoría de configuración',
'A', 'Policy Initiative agrupa definiciones de policy bajo un objetivo común.', 'facil'),

(6, 'Sobre bloqueos de recursos en Azure, ¿cuál afirmación es correcta?',
'Un recurso no puede tener más de un bloqueo de eliminación nunca',
'Los recursos heredan bloqueos aplicados al Resource Group',
'Un bloqueo ReadOnly impide por completo añadir cualquier otro bloqueo',
'Los bloqueos no afectan operaciones del plano de control en ARM',
'B', 'Los bloqueos del Resource Group se heredan por los recursos hijos.', 'facil'),

(6, '¿Dónde puedes ver postura y recomendaciones de cumplimiento normativo en Azure?',
'Azure Advisor exclusivamente, ya que reemplaza paneles de seguridad',
'Azure Analysis Services con informes de cumplimiento listos para auditoría',
'Azure Monitor Insights sin integración con controles normativos',
'Microsoft Defender for Cloud con paneles de secure score y cumplimiento',
'D', 'Defender for Cloud muestra recomendaciones y cumplimiento de estándares.', 'facil'),

(6, '¿Qué relación estándar/organización es correcta?',
'ISO define estándares internacionales en múltiples industrias y sectores',
'NIST es una política europea de privacidad para datos personales',
'GDPR es una nube dedicada para agencias federales de Estados Unidos',
'Azure Government es una organización global de normalización industrial',
'A', 'ISO es organismo internacional de estándares; otras opciones mezclan conceptos.', 'facil'),

(6, 'Con 5000 usuarios de AD local y migración a Azure, ¿qué minimiza impacto al usuario?',
'Forzar cambio de contraseña simultáneo para todos antes de migrar',
'Sincronizar cuentas de Active Directory local con Azure AD',
'Crear usuarios invitados en Azure AD para cada cuenta interna existente',
'Aplicar MFA obligatorio primero sin sincronizar identidades corporativas',
'B', 'La sincronización con Azure AD minimiza fricción para usuarios existentes.', 'facil'),

(6, 'Para permitir acceso solo desde dispositivos con parches recientes, implementa:',
'Política de acceso condicional integrada con estado de cumplimiento del dispositivo',
'Azure Bastion para validar nivel de parche antes de autenticar usuarios',
'Azure Firewall con inspección de endpoint y evaluación de actualizaciones',
'Azure Policy para bloquear inicios de sesión de Azure AD directamente',
'A', 'Conditional Access permite exigir cumplimiento del dispositivo para acceso.', 'medio'),

(6, '¿A qué servicio debe conectarse una app para obtener tokens de seguridad?',
'Cuenta de Azure Storage configurada con acceso SAS de larga duración',
'Azure Active Directory (Microsoft Entra ID) como proveedor de identidad',
'Azure Key Vault como emisor OAuth principal de acceso de usuario',
'Un almacén local de certificados sin integración de identidad federada',
'B', 'Los tokens de autenticación/autorización se obtienen desde Entra ID.', 'facil'),

(6, '¿Qué tarea puedes realizar con Azure Advisor?',
'Integrar AD local y Entra ID con sincronización de identidades completa',
'Estimar costos iniciales con detalle de arquitectura en la calculadora',
'Recibir recomendaciones para mejorar seguridad, coste y rendimiento',
'Descubrir automáticamente servidores on-prem y ejecutar migración asistida',
'C', 'Advisor entrega recomendaciones de buenas prácticas en varias categorías.', 'facil'),

(6, 'Sobre servicios Azure en versión preliminar (preview), ¿qué afirmación es correcta?',
'Las previews privadas siempre usan un portal Azure completamente distinto',
'Las previews públicas están recomendadas para producción crítica regulada',
'Las previews públicas incluyen SLA completo equivalente a GA generalmente',
'Las features preview pueden carecer de SLA y no se recomiendan para producción',
'D', 'En preview suele no haber SLA y se evita para cargas críticas.', 'facil'),

(6, 'Para generar informes de facturación por oficina, ¿qué usar antes en ARM?',
'Etiquetas (tags) para clasificar recursos por oficina o centro de coste',
'Plantillas ARM, porque son el mecanismo principal de imputación financiera',
'Bloqueos de recursos para separar facturación entre departamentos',
'Políticas con efecto append como único método de cost allocation',
'A', 'Las etiquetas permiten agrupar y reportar consumo por unidad organizativa.', 'facil'),

(6, 'Sobre costos y reservas en Azure, ¿qué afirmación es correcta?',
'Dos VMs B2s siempre costarán igual cada mes sin importar uso real',
'Las Azure Reservations suelen reducir coste frente a pago por uso',
'Al detener una VM se eliminan permanentemente todos los cargos asociados',
'Las reservas solo aplican a almacenamiento y no a recursos de cómputo',
'B', 'Las reservas pueden reducir el costo de cargas estables.', 'facil'),

(6, '¿Cuál fórmula representa el cálculo de porcentaje de uptime mensual?',
'(Minutos totales del mes - minutos de caída) / minutos totales * 100',
'(Minutos de caída - 60) - 99.99 para estimar disponibilidad mensual',
'1440 - 1440 para cualquier mes porque la disponibilidad es fija',
'(Minutos de caída / 100) * minutos totales como porcentaje final',
'A', 'La disponibilidad se calcula restando downtime al total y normalizando.', 'facil'),

(6, 'Si necesitas redundancia geográfica legible en secundario, ¿qué almacenamiento recomiendas?',
'GRS, que replica geográficamente pero no habilita lectura en secundario',
'RA-GRS para replicación geográfica con acceso de solo lectura secundario',
'ZRS, que replica por zonas pero no por región geográfica secundaria',
'LRS, que mantiene copias en un único datacenter de una región',
'B', 'RA-GRS ofrece réplica geográfica con lectura desde región secundaria.', 'facil'),

(6, 'Con plan de soporte básico y buscando minimizar coste para revisión arquitectónica, recomienda:',
'Premier, pensado para necesidades empresariales avanzadas de mayor coste',
'Developer, orientado principalmente a entornos de prueba no críticos',
'Professional Direct, opción intermedia con asesoría más completa que básica',
'Standard, con respuesta técnica ampliada manteniendo coste menor que Premier',
'C', 'Professional Direct suele equilibrar soporte técnico avanzado y costo frente a Premier.', 'medio');